<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250427120202 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE planet ADD resized JSON DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE planet ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE planet ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE voyage ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE voyage ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE voyage ALTER leave_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN voyage.leave_at IS ''
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE voyage ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE voyage ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE voyage ALTER leave_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN voyage.leave_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE planet DROP resized
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE planet ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE planet ALTER id DROP IDENTITY
        SQL);
    }
}
