<?php

namespace App\Tests\Crawl;

use PHPUnit\Framework\Attributes\TestDox;
use PHPUnit\Framework\Attributes\TestWith;
use Survos\CrawlerBundle\Tests\BaseVisitLinksTest;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CrawlAsVisitorTest extends BaseVisitLinksTest
{
	#[TestDox('/$method $url ($route)')]
	#[TestWith(['', 'App\Entity\User', '/', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/', 200])]
	#[TestWith(['', 'App\Entity\User', '/about', 200])]
	#[TestWith(['', 'App\Entity\User', '/swiper', 200])]
	#[TestWith(['', 'App\Entity\User', '/onsen', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/1', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/2', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/3', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/4', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/5', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/6', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/7', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/8', 200])]
	#[TestWith(['', 'App\Entity\User', '/planet/9', 200])]
	#[TestWith(['', 'App\Entity\User', '/?sort=purpose&sortDirection=asc', 200])]
	#[TestWith(['', 'App\Entity\User', '/?sort=leaveAt&sortDirection=asc', 200])]
	#[TestWith(['', 'App\Entity\User', '/?page=2', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/60', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/59', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/58', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/57', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/56', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/55', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/54', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/53', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/52', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/51', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/50', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/49', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/48', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/47', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/46', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/45', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/44', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/43', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/42', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/41', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/40', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/39', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/38', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/37', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/36', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/35', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/34', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/33', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/32', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/31', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/30', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/29', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/28', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/27', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/26', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/25', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/24', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/23', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/22', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/21', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/20', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/19', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/18', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/17', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/16', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/15', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/14', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/13', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/12', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/11', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/10', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/9', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/8', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/7', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/6', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/5', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/4', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/3', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/2', 200])]
	#[TestWith(['', 'App\Entity\User', '/voyage/1', 200])]
	#[TestWith(['', 'App\Entity\User', '/?sort=purpose&sortDirection=desc', 200])]
	#[TestWith(['', 'App\Entity\User', '/?sort=purpose&sortDirection=asc&page=2', 200])]
	public function testRoute(string $username, string $userClassName, string $url, string|int|null $expected): void
	{
		parent::testWithLogin($username, $userClassName, $url, (int)$expected);
	}
}
